// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20260102060539_comparisons2")]
    partial class comparisons2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Comparisons", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Comparable")
                        .HasColumnType("boolean")
                        .HasColumnName("comporable");

                    b.Property<string>("Market_1_Id")
                        .HasColumnType("text")
                        .HasColumnName("market_1_id");

                    b.Property<string>("Market_2_Id")
                        .HasColumnType("text")
                        .HasColumnName("market_2_id");

                    b.HasKey("Id");

                    b.ToTable("comparisons");
                });

            modelBuilder.Entity("Data.Entities.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Data.Entities.Market", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("BestAsk")
                        .HasColumnType("numeric")
                        .HasColumnName("best_ask");

                    b.Property<decimal>("BestBid")
                        .HasColumnType("numeric")
                        .HasColumnName("best_bid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Outcomes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("outcomes");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("markets");
                });

            modelBuilder.Entity("Data.Entities.Market", b =>
                {
                    b.HasOne("Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
